pepperoni = Topping.create(name: "pepperoni")
jalapeno = Topping.create(name: "jalapeno")
olives = Topping.create(name: "olives")
canadian_bacon = Topping.create(name: "canadian bacon")
onions = Topping.create(name: "onions")
bacon = Topping.create(name: "bacon")
pineapple = Topping.create(name: "pineapple")
bell_peppers = Topping.create(name: "bell peppers")
sausage = Topping.create(name: "sausage")
mushroom = Topping.create(name: "mushroom")

aysans_order = Pizza.create(name: "Pepperoni Pineapple", desc: "Yummy in my tummy")
timmys_order = Pizza.create(name: "Spicy slice", desc: "Super spicy, but super yummy")
willows_order = Pizza.create(name: "Stacked", desc: "I want it all on my pizza")

PizzaTopping.create(pizza_id: aysans_order.id, topping_id: pepperoni.id)
PizzaTopping.create(pizza_id: aysans_order.id, topping_id: pineapple.id)
PizzaTopping.create(pizza_id: aysans_order.id, topping_id: jalapeno.id)

PizzaTopping.create(pizza_id: timmys_order.id, topping_id: jalapeno.id)
PizzaTopping.create(pizza_id: timmys_order.id, topping_id: sausage.id)
PizzaTopping.create(pizza_id: timmys_order.id, topping_id: mushroom.id)
PizzaTopping.create(pizza_id: timmys_order.id, topping_id: olives.id)

PizzaTopping.create(pizza_id: willows_order.id, topping_id: olives.id)
PizzaTopping.create(pizza_id: willows_order.id, topping_id: mushroom.id)
PizzaTopping.create(pizza_id: willows_order.id, topping_id: bell_peppers.id)
PizzaTopping.create(pizza_id: willows_order.id, topping_id: bacon.id)
PizzaTopping.create(pizza_id: willows_order.id, topping_id: sausage.id)
PizzaTopping.create(pizza_id: willows_order.id, topping_id: onions.id)
PizzaTopping.create(pizza_id: willows_order.id, topping_id: pepperoni.id)