source "https://rubygems.org"

gem "rake" 
gem "rspec"
gem "require_all"
gem 'sqlite3'
gem 'activerecord'
gem 'sinatra-activerecord' 
gem 'sinatra'
gem "rack-cors"
gem "activesupport", "~> 6.1"


group :development do
  gem "rerun"
  gem "pry"
end