source "https://rubygems.org"

# Specify your gem's dependencies in ruby_fundamentals.gemspec

gem "rake"
gem "rspec"
gem "require_all"
gem "pry"
gem 'sqlite3'
gem 'activerecord'
gem 'sinatra-activerecord'